webtalk_init -webtalk_dir D:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.sim/sim_1/behav/xsim/xsim.dir/dual_port_ram_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 10 12:26:40 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f51b2136-b3fd-4651-a618-330216624aef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "583638d6085245c7b18b6f9e74c99b58" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7516_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3274399847 -regid "" -xml D:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.sim/sim_1/behav/xsim/xsim.dir/dual_port_ram_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.sim/sim_1/behav/xsim/xsim.dir/dual_port_ram_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.sim/sim_1/behav/xsim/xsim.dir/dual_port_ram_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
