# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VHDL_tutorial_problems_LFT/Problem_3/dual_port_ram/true_dual_port_ram/true_dual_port_ram.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
